### ISSUE TITLE
bug: error when run preprocess.py

### ISSUE THREAD

**Issue by wkgreat** [zealscott/ST2Vec#2]
Traceback (most recent call last):
  File "E:\codes\github\ST2Vec\preprocess.py", line 203, in <module>
    prepare_dataset(trajfile=str(config["traj_file"]), timefile=str(config["time_file"]), kseg=config["kseg"])
  File "E:\codes\github\ST2Vec\preprocess.py", line 34, in prepare_dataset
    node_list_int = np.array(node_list_int)
                    ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (29830,) + inhomogeneous part.

**Comment by z7d1** [comment]
The version of `numpy` changes to 1.23.0 can solve it. But get more warnings.
```bash
Epoch: 17 	Loss: 0.7527
Epoch: 18 	Loss: 0.7527
Epoch: 19 	Loss: 0.7526
Epoch: 20 	Loss: 0.7526
Node embedding saved at: ./data/tdrive/node_features.npy
D:\workspace\ST2Vec\preprocess.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  node_list_int = np.array(node_list_int)
D:\workspace\ST2Vec\preprocess.py:45: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  time_list_int = np.array(time_list_int)
complete: ksegment
D:\workspace\ST2Vec\preprocess.py:78: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  coor_trajs = np.array(coor_trajs)
D:\env\anaconda3\envs\ST2Vec\lib\site-packages\torch\serialization.py:1101: SourceChangeWarning: source code of class 'Model.Date2Vec' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\env\anaconda3\envs\ST2Vec\lib\site-packages\torch\serialization.py:1101: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\env\anaconda3\envs\ST2Vec\lib\site-packages\torch\serialization.py:1101: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\workspace\ST2Vec\preprocess.py:110: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  all_list = np.array(all_list)
29830
```

**Comment by yuanjun-liu** [comment]
np.array(node_list_int,dtype=object)
